export const CART_ERROR_CODES = {
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_NOT_ACTIVE: 'CART_NOT_ACTIVE',
  CART_EXPIRED: 'CART_EXPIRED',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_INVALID_QUANTITY: 'CART_INVALID_QUANTITY',
  CART_CURRENCY_MISMATCH: 'CART_CURRENCY_MISMATCH',
  CART_VARIANT_NOT_AVAILABLE: 'CART_VARIANT_NOT_AVAILABLE',
  CART_INSUFFICIENT_STOCK: 'CART_INSUFFICIENT_STOCK',
  CART_PRICE_NOT_AVAILABLE: 'CART_PRICE_NOT_AVAILABLE',
  CART_GUEST_TOKEN_INVALID: 'CART_GUEST_TOKEN_INVALID',
  CART_CUSTOMER_MISMATCH: 'CART_CUSTOMER_MISMATCH',
  CART_TENANT_MISMATCH: 'CART_TENANT_MISMATCH',
  CART_VERSION_CONFLICT: 'CART_VERSION_CONFLICT',
  CART_INVALID_OWNER: 'CART_INVALID_OWNER',
} as const;

export class CartException extends Error {
  public readonly code: string;
  constructor(code: string, message: string) {
    super(message);
    this.name = 'CartException';
    this.code = code;
  }
}
