export const STORAGE_TOKENS = {
  CONFIG: Symbol('STORAGE_CONFIG'),
  DRIVER: Symbol('STORAGE_DRIVER'),
  MANAGER: Symbol('STORAGE_MANAGER'),
  SERVICE: Symbol('STORAGE_SERVICE'),
  HEALTH: Symbol('STORAGE_HEALTH'),
  LOCAL_DRIVER: Symbol('STORAGE_LOCAL_DRIVER'),
  S3_DRIVER: Symbol('STORAGE_S3_DRIVER'),
  MEMORY_DRIVER: Symbol('STORAGE_MEMORY_DRIVER'),
} as const;
