export const STORAGE_DEFAULTS = {
  LOCAL_PATH: './storage',
  MAX_FILE_SIZE: 10 * 1024 * 1024,
  SIGNED_URL_EXPIRY: 3600,
  MAX_UPLOAD_ATTEMPTS: 3,
  LIST_MAX_KEYS: 1000,
  PART_SIZE: 5 * 1024 * 1024,
  MAX_PARTS: 10000,
  HEALTH_CHECK_TIMEOUT: 5000,
  DEFAULT_REGION: 'auto',
  FORCE_PATH_STYLE: true,
  ALLOWED_MIME_TYPES: [
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/avif',
    'application/pdf',
    'text/csv',
    'application/json',
    'text/plain',
  ],
  STORAGE_CLASS_STANDARD: 'STANDARD',
  CACHE_CONTROL_MAX_AGE: 31536000,
} as const;
