export const PRODUCTS_CONSTANTS = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 255,
  SLUG_MAX_LENGTH: 255,
  SHORT_DESCRIPTION_MAX_LENGTH: 500,
  DESCRIPTION_MAX_LENGTH: 10000,
  SEO_TITLE_MAX_LENGTH: 70,
  SEO_DESCRIPTION_MAX_LENGTH: 160,
  WARRANTY_MIN_MONTHS: 0,
  WARRANTY_MAX_MONTHS: 120,
} as const;
