export const MFA_ERROR_CODES = {
  MFA_NOT_ENABLED: 'MFA_NOT_ENABLED',
  MFA_ALREADY_ENABLED: 'MFA_ALREADY_ENABLED',
  MFA_CHALLENGE_EXPIRED: 'MFA_CHALLENGE_EXPIRED',
  MFA_CHALLENGE_INVALID: 'MFA_CHALLENGE_INVALID',
  MFA_VERIFICATION_FAILED: 'MFA_VERIFICATION_FAILED',
  MFA_INVALID_TOTP_CODE: 'MFA_INVALID_TOTP_CODE',
  MFA_INVALID_BACKUP_CODE: 'MFA_INVALID_BACKUP_CODE',
  MFA_BACKUP_CODE_ALREADY_USED: 'MFA_BACKUP_CODE_ALREADY_USED',
  MFA_NO_BACKUP_CODES: 'MFA_NO_BACKUP_CODES',
  MFA_TRUSTED_DEVICE_EXPIRED: 'MFA_TRUSTED_DEVICE_EXPIRED',
  MFA_TRUSTED_DEVICE_NOT_FOUND: 'MFA_TRUSTED_DEVICE_NOT_FOUND',
  MFA_INVALID_RECOVERY_TOKEN: 'MFA_INVALID_RECOVERY_TOKEN',
  MFA_RECOVERY_TOKEN_EXPIRED: 'MFA_RECOVERY_TOKEN_EXPIRED',
  MFA_SECRET_GENERATION_FAILED: 'MFA_SECRET_GENERATION_FAILED',
  MFA_CLOCK_DRIFT_DETECTED: 'MFA_CLOCK_DRIFT_DETECTED',
  MFA_METHOD_NOT_SUPPORTED: 'MFA_METHOD_NOT_SUPPORTED',
  MFA_MAX_ATTEMPTS_EXCEEDED: 'MFA_MAX_ATTEMPTS_EXCEEDED',
  MFA_ENROLLMENT_NOT_FOUND: 'MFA_ENROLLMENT_NOT_FOUND',
  MFA_METHOD_ALREADY_ENROLLED: 'MFA_METHOD_ALREADY_ENROLLED',
} as const;

export class MfaException extends Error {
  public readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'MfaException';
    this.code = code;
  }
}
