export const BRAND_ERROR_CODES = {
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  BRAND_SLUG_ALREADY_EXISTS: 'BRAND_SLUG_ALREADY_EXISTS',
  BRAND_INVALID_STATUS_TRANSITION: 'BRAND_INVALID_STATUS_TRANSITION',
  BRAND_INVALID_URL: 'BRAND_INVALID_URL',
  BRAND_TENANT_MISMATCH: 'BRAND_TENANT_MISMATCH',
  BRAND_HAS_PRODUCTS: 'BRAND_HAS_PRODUCTS',
  BRAND_VERSION_CONFLICT: 'BRAND_VERSION_CONFLICT',
  BRAND_INVALID_DATA: 'BRAND_INVALID_DATA',
  BRAND_DELETED: 'BRAND_DELETED',
  BRAND_ARCHIVED_CANNOT_BE_PUBLIC: 'BRAND_ARCHIVED_CANNOT_BE_PUBLIC',
} as const;

export class BrandException extends Error {
  public readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'BrandException';
    this.code = code;
  }
}
