export const CHECKOUT_ERROR_CODES = {
  CHECKOUT_NOT_FOUND: 'CHECKOUT_NOT_FOUND',
  CHECKOUT_NOT_ACTIVE: 'CHECKOUT_NOT_ACTIVE',
  CHECKOUT_EXPIRED: 'CHECKOUT_EXPIRED',
  CHECKOUT_INVALID_CART: 'CHECKOUT_INVALID_CART',
  CHECKOUT_EMPTY_CART: 'CHECKOUT_EMPTY_CART',
  CHECKOUT_INVALID_ADDRESS: 'CHECKOUT_INVALID_ADDRESS',
  CHECKOUT_PRICE_CHANGED: 'CHECKOUT_PRICE_CHANGED',
  CHECKOUT_INSUFFICIENT_STOCK: 'CHECKOUT_INSUFFICIENT_STOCK',
  CHECKOUT_SHIPPING_METHOD_INVALID: 'CHECKOUT_SHIPPING_METHOD_INVALID',
  CHECKOUT_PAYMENT_METHOD_INVALID: 'CHECKOUT_PAYMENT_METHOD_INVALID',
  CHECKOUT_CURRENCY_MISMATCH: 'CHECKOUT_CURRENCY_MISMATCH',
  CHECKOUT_ALREADY_COMPLETED: 'CHECKOUT_ALREADY_COMPLETED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  ORDER_NUMBER_CONFLICT: 'ORDER_NUMBER_CONFLICT',
  CHECKOUT_TENANT_MISMATCH: 'CHECKOUT_TENANT_MISMATCH',
  CHECKOUT_VERSION_CONFLICT: 'CHECKOUT_VERSION_CONFLICT',
  CHECKOUT_NO_ADDRESS: 'CHECKOUT_NO_ADDRESS',
  CHECKOUT_NO_SHIPPING: 'CHECKOUT_NO_SHIPPING',
  CHECKOUT_NO_PAYMENT: 'CHECKOUT_NO_PAYMENT',
} as const;

export class CheckoutException extends Error {
  public readonly code: string;
  constructor(code: string, message: string) {
    super(message);
    this.name = 'CheckoutException';
    this.code = code;
  }
}
