export const REVIEW_ERROR_CODES = {
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_INVALID_RATING: 'REVIEW_INVALID_RATING',
  REVIEW_INVALID_CONTENT: 'REVIEW_INVALID_CONTENT',
  REVIEW_PRODUCT_NOT_FOUND: 'REVIEW_PRODUCT_NOT_FOUND',
  REVIEW_VARIANT_MISMATCH: 'REVIEW_VARIANT_MISMATCH',
  REVIEW_PURCHASE_NOT_VERIFIED: 'REVIEW_PURCHASE_NOT_VERIFIED',
  REVIEW_ORDER_INVALID: 'REVIEW_ORDER_INVALID',
  REVIEW_NOT_EDITABLE: 'REVIEW_NOT_EDITABLE',
  REVIEW_INVALID_STATUS_TRANSITION: 'REVIEW_INVALID_STATUS_TRANSITION',
  REVIEW_ALREADY_APPROVED: 'REVIEW_ALREADY_APPROVED',
  REVIEW_REJECTION_REASON_REQUIRED: 'REVIEW_REJECTION_REASON_REQUIRED',
  REVIEW_RESPONSE_ALREADY_EXISTS: 'REVIEW_RESPONSE_ALREADY_EXISTS',
  REVIEW_RESPONSE_NOT_FOUND: 'REVIEW_RESPONSE_NOT_FOUND',
  REVIEW_VOTE_ALREADY_EXISTS: 'REVIEW_VOTE_ALREADY_EXISTS',
  REVIEW_SELF_VOTE_FORBIDDEN: 'REVIEW_SELF_VOTE_FORBIDDEN',
  REVIEW_CUSTOMER_MISMATCH: 'REVIEW_CUSTOMER_MISMATCH',
  REVIEW_TENANT_MISMATCH: 'REVIEW_TENANT_MISMATCH',
  REVIEW_VERSION_CONFLICT: 'REVIEW_VERSION_CONFLICT',
} as const;

export class ReviewException extends Error {
  constructor(public readonly code: keyof typeof REVIEW_ERROR_CODES | string, message: string) { super(message); this.name = 'ReviewException'; }
}
