export const WISHLIST_ERROR_CODES = {
  WISHLIST_NOT_FOUND: 'WISHLIST_NOT_FOUND',
  WISHLIST_NOT_ACTIVE: 'WISHLIST_NOT_ACTIVE',
  WISHLIST_ARCHIVED: 'WISHLIST_ARCHIVED',
  WISHLIST_EXPIRED: 'WISHLIST_EXPIRED',
  WISHLIST_NAME_ALREADY_EXISTS: 'WISHLIST_NAME_ALREADY_EXISTS',
  WISHLIST_LIMIT_EXCEEDED: 'WISHLIST_LIMIT_EXCEEDED',
  WISHLIST_ITEM_NOT_FOUND: 'WISHLIST_ITEM_NOT_FOUND',
  WISHLIST_ITEM_ALREADY_EXISTS: 'WISHLIST_ITEM_ALREADY_EXISTS',
  WISHLIST_ITEM_LIMIT_EXCEEDED: 'WISHLIST_ITEM_LIMIT_EXCEEDED',
  WISHLIST_PRODUCT_NOT_AVAILABLE: 'WISHLIST_PRODUCT_NOT_AVAILABLE',
  WISHLIST_VARIANT_REQUIRED: 'WISHLIST_VARIANT_REQUIRED',
  WISHLIST_VARIANT_NOT_AVAILABLE: 'WISHLIST_VARIANT_NOT_AVAILABLE',
  WISHLIST_INSUFFICIENT_STOCK: 'WISHLIST_INSUFFICIENT_STOCK',
  WISHLIST_GUEST_TOKEN_INVALID: 'WISHLIST_GUEST_TOKEN_INVALID',
  WISHLIST_CUSTOMER_MISMATCH: 'WISHLIST_CUSTOMER_MISMATCH',
  WISHLIST_TENANT_MISMATCH: 'WISHLIST_TENANT_MISMATCH',
  WISHLIST_VERSION_CONFLICT: 'WISHLIST_VERSION_CONFLICT',
  WISHLIST_MERGE_CONFLICT: 'WISHLIST_MERGE_CONFLICT',
} as const;

export class WishlistException extends Error {
  constructor(public readonly code: string, message: string) { super(message); this.name = 'WishlistException'; }
}
