export const ORDER_ERROR_CODES = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS_TRANSITION: 'ORDER_INVALID_STATUS_TRANSITION',
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  ORDER_ALREADY_DELIVERED: 'ORDER_ALREADY_DELIVERED',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  ORDER_NOT_SHIPPABLE: 'ORDER_NOT_SHIPPABLE',
  ORDER_NOT_DELIVERABLE: 'ORDER_NOT_DELIVERABLE',
  ORDER_PAYMENT_ALREADY_CONFIRMED: 'ORDER_PAYMENT_ALREADY_CONFIRMED',
  ORDER_PAYMENT_NOT_CONFIRMED: 'ORDER_PAYMENT_NOT_CONFIRMED',
  ORDER_RESERVATION_RELEASE_FAILED: 'ORDER_RESERVATION_RELEASE_FAILED',
  ORDER_NOTE_NOT_FOUND: 'ORDER_NOTE_NOT_FOUND',
  ORDER_NOTE_FORBIDDEN: 'ORDER_NOTE_FORBIDDEN',
  ORDER_CANCELLATION_ALREADY_EXISTS: 'ORDER_CANCELLATION_ALREADY_EXISTS',
  ORDER_TRACKING_INVALID: 'ORDER_TRACKING_INVALID',
  ORDER_TENANT_MISMATCH: 'ORDER_TENANT_MISMATCH',
  ORDER_CUSTOMER_MISMATCH: 'ORDER_CUSTOMER_MISMATCH',
  ORDER_VERSION_CONFLICT: 'ORDER_VERSION_CONFLICT',
  ORDER_INVALID_NOTE_VISIBILITY: 'ORDER_INVALID_NOTE_VISIBILITY',
  ORDER_CANNOT_MODIFY_TERMINAL: 'ORDER_CANNOT_MODIFY_TERMINAL',
} as const;

export class OrderException extends Error {
  public readonly code: string;
  constructor(code: string, message: string) {
    super(message);
    this.name = 'OrderException';
    this.code = code;
  }
}
