export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  SESSION_INVALID: 'AUTH_SESSION_INVALID',
  USER_INACTIVE: 'AUTH_USER_INACTIVE',
  USER_SUSPENDED: 'AUTH_USER_SUSPENDED',
  USER_DELETED: 'AUTH_USER_DELETED',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  PASSWORD_POLICY_VIOLATION: 'AUTH_PASSWORD_POLICY_VIOLATION',
  RATE_LIMIT_EXCEEDED: 'AUTH_RATE_LIMIT_EXCEEDED',
  INVALID_TOKEN_TYPE: 'AUTH_INVALID_TOKEN_TYPE',
  MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  CLOCK_DRIFT_DETECTED: 'AUTH_CLOCK_DRIFT_DETECTED',
} as const;

export class AuthenticationException extends Error {
  public readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'AuthenticationException';
    this.code = code;
  }
}
