export const HTTP_DEFAULTS = {
  DRIVER: 'undici',
  BASE_URL: '',
  TIMEOUT: 10_000,
  CONNECT_TIMEOUT: 3_000,
  READ_TIMEOUT: 10_000,
  WRITE_TIMEOUT: 10_000,
  MAX_RETRIES: 3,
  RETRY_DELAY: 500,
  RETRY_JITTER: true,
  RETRY_STRATEGY: 'exponential',
  KEEP_ALIVE: true,
  MAX_CONNECTIONS: 10,
  DNS_CACHE: true,
  DNS_CACHE_TTL: 60_000,
  POOL_SIZE: 10,
  PIPELINING: 0,
  DEFAULT_HEADERS: {
    'user-agent': 'Tienda-HTTP/1.0',
    'accept': 'application/json',
    'content-type': 'application/json',
  },
  MAX_REDIRECTS: 5,
  PREFER_HTTP2: false,
  UPLOAD_TIMEOUT: 120_000,
} as const;
