export const PRODUCT_ERROR_CODES = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_ALREADY_EXISTS: 'PRODUCT_SLUG_ALREADY_EXISTS',
  PRODUCT_INVALID_STATUS_TRANSITION: 'PRODUCT_INVALID_STATUS_TRANSITION',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  PRODUCT_INVALID_DATA: 'PRODUCT_INVALID_DATA',
  PRODUCT_TENANT_MISMATCH: 'PRODUCT_TENANT_MISMATCH',
  PRODUCT_VERSION_CONFLICT: 'PRODUCT_VERSION_CONFLICT',
  PRODUCT_INVALID_NAME: 'PRODUCT_INVALID_NAME',
  PRODUCT_INVALID_SLUG: 'PRODUCT_INVALID_SLUG',
  PRODUCT_INVALID_VISIBILITY: 'PRODUCT_INVALID_VISIBILITY',
  PRODUCT_INVALID_WARRANTY: 'PRODUCT_INVALID_WARRANTY',
  PRODUCT_INVALID_SEO: 'PRODUCT_INVALID_SEO',
} as const;

export class ProductException extends Error {
  public readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'ProductException';
    this.code = code;
  }
}
