export const WISHLIST_DEFAULT_NAME = 'Favoritos';
export const WISHLIST_MAX_LISTS_PER_CUSTOMER = 10;
export const WISHLIST_MAX_ITEMS_PER_LIST = 200;
export const WISHLIST_GUEST_EXPIRATION_DAYS = 30;
export const WISHLIST_MAX_NAME_LENGTH = 120;
export const WISHLIST_MAX_NOTE_LENGTH = 1000;
