export const MAIL_ERROR_CODES = {
  SEND_FAILED: 'MAIL_001',
  CONNECTION_FAILED: 'MAIL_002',
  AUTHENTICATION_FAILED: 'MAIL_003',
  PROVIDER_UNAVAILABLE: 'MAIL_004',
  TIMEOUT: 'MAIL_005',
  INVALID_ADDRESS: 'MAIL_006',
  TEMPLATE_ERROR: 'MAIL_007',
  RENDER_ERROR: 'MAIL_008',
  CONFIGURATION_ERROR: 'MAIL_009',
  RATE_LIMIT_EXCEEDED: 'MAIL_010',
  ATTACHMENT_TOO_LARGE: 'MAIL_011',
  BULK_PARTIAL_FAILURE: 'MAIL_012',
} as const;
