export const MAIL_TOKENS = {
  CONFIG: Symbol('MAIL_CONFIG'),
  PROVIDER: Symbol('MAIL_PROVIDER'),
  MANAGER: Symbol('MAIL_MANAGER'),
  SERVICE: Symbol('MAIL_SERVICE'),
  HEALTH: Symbol('MAIL_HEALTH'),
  SMTP_DRIVER: Symbol('MAIL_SMTP_DRIVER'),
  SES_DRIVER: Symbol('MAIL_SES_DRIVER'),
  SENDGRID_DRIVER: Symbol('MAIL_SENDGRID_DRIVER'),
  MAILGUN_DRIVER: Symbol('MAIL_MAILGUN_DRIVER'),
  RESEND_DRIVER: Symbol('MAIL_RESEND_DRIVER'),
  LOG_DRIVER: Symbol('MAIL_LOG_DRIVER'),
  TEMPLATE_ENGINE: Symbol('MAIL_TEMPLATE_ENGINE'),
} as const;
