export const AUTHZ_ERROR_CODES = {
  PERMISSION_DENIED: 'AUTHZ_PERMISSION_DENIED',
  ROLE_NOT_FOUND: 'AUTHZ_ROLE_NOT_FOUND',
  PERMISSION_NOT_FOUND: 'AUTHZ_PERMISSION_NOT_FOUND',
  POLICY_NOT_FOUND: 'AUTHZ_POLICY_NOT_FOUND',
  INVALID_PERMISSION_FORMAT: 'AUTHZ_INVALID_PERMISSION_FORMAT',
  INVALID_ROLE_NAME: 'AUTHZ_INVALID_ROLE_NAME',
  INVALID_POLICY_NAME: 'AUTHZ_INVALID_POLICY_NAME',
  INVALID_RESOURCE_NAME: 'AUTHZ_INVALID_RESOURCE_NAME',
  INVALID_ACTION_NAME: 'AUTHZ_INVALID_ACTION_NAME',
  INVALID_SCOPE: 'AUTHZ_INVALID_SCOPE',
  CIRCULAR_ROLE_HIERARCHY: 'AUTHZ_CIRCULAR_ROLE_HIERARCHY',
  DUPLICATE_PERMISSION: 'AUTHZ_DUPLICATE_PERMISSION',
  CANNOT_MODIFY_SYSTEM_ROLE: 'AUTHZ_CANNOT_MODIFY_SYSTEM_ROLE',
  MAX_ROLE_DEPTH_EXCEEDED: 'AUTHZ_MAX_ROLE_DEPTH_EXCEEDED',
  ROLE_ALREADY_ASSIGNED: 'AUTHZ_ROLE_ALREADY_ASSIGNED',
  RESOURCE_NOT_REGISTERED: 'AUTHZ_RESOURCE_NOT_REGISTERED',
  ACTION_NOT_REGISTERED: 'AUTHZ_ACTION_NOT_REGISTERED',
} as const;

export class AuthorizationException extends Error {
  public readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'AuthorizationException';
    this.code = code;
  }
}
