export const VALIDATION_ERROR_PREFIX = 'VALIDATION';

export const DEFAULT_VALIDATION_MODE = 'strip' as const;

export const MAX_VALIDATION_ERRORS = 10;

export const VALIDATION_ERROR_CODES = {
  INVALID_TYPE: 'VALIDATION_001',
  INVALID_FORMAT: 'VALIDATION_002',
  MISSING_FIELD: 'VALIDATION_003',
  TOO_SHORT: 'VALIDATION_004',
  TOO_LONG: 'VALIDATION_005',
  OUT_OF_RANGE: 'VALIDATION_006',
  INVALID_ENUM: 'VALIDATION_007',
  CUSTOM: 'VALIDATION_008',
} as const;
