export { ApiKeysModule } from './api-keys.module';
export { DomainEvent, KeyCreatedEvent, KeyRotatedEvent, KeyRevokedEvent, KeyExpiredEvent, KeyUsedEvent, ServiceAccountCreatedEvent, ServiceAccountDisabledEvent, MachineAuthenticatedEvent } from './domain/events';
export { ApiKeyException, API_KEY_ERROR_CODES } from './domain/exceptions';
export { ApiKeyId, KeyPrefix, ServiceAccountId, Scope } from './domain/value-objects';
export { ApiKeyDomainService, ServiceAccountDomainService, ScopeResolver } from './domain/services';
export type { IApiKeyStore, IServiceAccountStore, IKeyHashingService, IKeyGeneratorService } from './domain/services/stores';
export type { ApiKey, ApiKeyCreateResult, ApiKeyStatus, ServiceAccount, ServiceAccountStatus, KeyValidationResult, KeyRotationResult, MachineAuthResult, ScopeDefinition } from './domain/types';
export { ApiKeyAppService } from './services';
export { KeyHashingService, KeyGeneratorService, InMemoryApiKeyStore, InMemoryServiceAccountStore } from './infrastructure';
export { ApiKeyGuard, ServiceAccountGuard, ScopeGuard, MachineAuthGuard } from './presentation/guards';
export { RequireApiKey, RequireScope, CurrentApiKey, CurrentServiceAccount } from './presentation/decorators';
export { ApiKeyEventHandler } from './events';
export { ApiKeyExceptionFilter } from './exceptions';
export { API_KEYS_CONSTANTS } from './constants';
export { validateApiKeyFormat, validateScope, validateScopes, validateDisplayName, validateServiceAccountName, validatePrefix, extractKeyFromHeader, formatKeyForDisplay } from './validators';
export { API_KEY_PROVIDERS } from './providers';
export type { IApiKeyService } from './application/interfaces';
export type { CreateApiKeyRequestDto, CreateApiKeyResponseDto, ApiKeyResponseDto, CreateServiceAccountRequestDto, ServiceAccountResponseDto, RotateKeyResponseDto, MachineAuthResponseDto, ScopeValidationResponseDto } from './application/dto';
export { CreateApiKeyCommand, ValidateApiKeyCommand, RotateApiKeyCommand, RevokeApiKeyCommand, CreateServiceAccountCommand, AssignScopeCommand, UpdateRolesCommand, UpdatePermissionsCommand } from './application/commands';
export { ApiKeyValidators } from './application/validators';
