export const SESSION_ERROR_CODES = {
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_INACTIVE: 'SESSION_INACTIVE',
  SESSION_OWNER_MISMATCH: 'SESSION_OWNER_MISMATCH',
  SESSION_LIMIT_EXCEEDED: 'SESSION_LIMIT_EXCEEDED',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_LIMIT_EXCEEDED: 'DEVICE_LIMIT_EXCEEDED',
  INVALID_SESSION_ID: 'INVALID_SESSION_ID',
  INVALID_DEVICE_ID: 'INVALID_DEVICE_ID',
  INVALID_IP_ADDRESS: 'INVALID_IP_ADDRESS',
  INVALID_USER_AGENT: 'INVALID_USER_AGENT',
  SESSION_PERSISTENCE_FAILED: 'SESSION_PERSISTENCE_FAILED',
} as const;

export class SessionException extends Error {
  public readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'SessionException';
    this.code = code;
  }
}
