export const CUSTOMER_ERROR_CODES = {
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_EMAIL_ALREADY_EXISTS: 'CUSTOMER_EMAIL_ALREADY_EXISTS',
  CUSTOMER_INVALID_EMAIL: 'CUSTOMER_INVALID_EMAIL',
  CUSTOMER_INVALID_PHONE: 'CUSTOMER_INVALID_PHONE',
  CUSTOMER_INVALID_STATUS_TRANSITION: 'CUSTOMER_INVALID_STATUS_TRANSITION',
  CUSTOMER_BLOCKED: 'CUSTOMER_BLOCKED',
  CUSTOMER_ARCHIVED: 'CUSTOMER_ARCHIVED',
  CUSTOMER_USER_ALREADY_LINKED: 'CUSTOMER_USER_ALREADY_LINKED',
  CUSTOMER_GUEST_CONVERSION_CONFLICT: 'CUSTOMER_GUEST_CONVERSION_CONFLICT',
  CUSTOMER_ADDRESS_NOT_FOUND: 'CUSTOMER_ADDRESS_NOT_FOUND',
  CUSTOMER_DEFAULT_ADDRESS_CONFLICT: 'CUSTOMER_DEFAULT_ADDRESS_CONFLICT',
  CUSTOMER_TAG_NOT_FOUND: 'CUSTOMER_TAG_NOT_FOUND',
  CUSTOMER_TAG_ALREADY_ASSIGNED: 'CUSTOMER_TAG_ALREADY_ASSIGNED',
  CUSTOMER_NOTE_NOT_FOUND: 'CUSTOMER_NOTE_NOT_FOUND',
  CUSTOMER_NOTE_FORBIDDEN: 'CUSTOMER_NOTE_FORBIDDEN',
  CUSTOMER_TENANT_MISMATCH: 'CUSTOMER_TENANT_MISMATCH',
  CUSTOMER_USER_MISMATCH: 'CUSTOMER_USER_MISMATCH',
  CUSTOMER_VERSION_CONFLICT: 'CUSTOMER_VERSION_CONFLICT',
} as const;

export class CustomerException extends Error {
  constructor(public readonly code: string, message: string) {
    super(message);
    this.name = 'CustomerException';
  }
}
