export const TENANT_ERROR_CODES = {
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_INACTIVE: 'TENANT_INACTIVE',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  BRANCH_INACTIVE: 'BRANCH_INACTIVE',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  CONTEXT_NOT_FOUND: 'CONTEXT_NOT_FOUND',
  CONTEXT_EXPIRED: 'CONTEXT_EXPIRED',
  INVALID_TENANT_ID: 'INVALID_TENANT_ID',
  INVALID_BRANCH_ID: 'INVALID_BRANCH_ID',
  INVALID_SLUG: 'INVALID_SLUG',
  TENANT_RESOLUTION_FAILED: 'TENANT_RESOLUTION_FAILED',
  CROSS_TENANT_ACCESS_DENIED: 'CROSS_TENANT_ACCESS_DENIED',
} as const;

export class TenantException extends Error {
  public readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'TenantException';
    this.code = code;
  }
}
