import { Order } from '../../../../../checkout/domain';
import type { OrderPrimitives } from '../../../../../checkout/domain';

export class PrismaOrderMapper {
  static toDomain(raw: any): Order {
    return Order.fromPrimitives({
      id: raw.id,
      tenantId: raw.tenantId,
      orderNumber: raw.orderNumber,
      cartId: raw.cartId,
      checkoutSessionId: raw.checkoutSessionId,
      customerId: raw.customerId,
      guestEmail: raw.guestEmail,
      status: raw.status,
      currency: raw.currency,
      subtotal: raw.subtotal,
      shippingAmount: raw.shippingAmount,
      discountAmount: raw.discountAmount,
      taxAmount: raw.taxAmount,
      total: raw.total,
      shippingMethodCode: raw.shippingMethodCode,
      paymentMethodCode: raw.paymentMethodCode,
      paymentStatus: raw.paymentStatus,
      fulfillmentStatus: raw.fulfillmentStatus,
      cancellationReason: raw.cancellationReason,
      cancelledAt: raw.cancelledAt,
      confirmedAt: raw.confirmedAt,
      processingStartedAt: raw.processingStartedAt,
      readyAt: raw.readyAt,
      shippedAt: raw.shippedAt,
      deliveredAt: raw.deliveredAt,
      expiredAt: raw.expiredAt,
      carrierCode: raw.carrierCode,
      trackingNumber: raw.trackingNumber,
      trackingUrl: raw.trackingUrl,
      version: raw.version,
      createdAt: raw.createdAt,
      updatedAt: raw.updatedAt,
      items: (raw.items ?? []).map((i: any) => ({
        id: i.id,
        orderId: i.orderId,
        productVariantId: i.productVariantId,
        sku: i.sku,
        productNameSnapshot: i.productNameSnapshot,
        variantNameSnapshot: i.variantNameSnapshot,
        quantity: i.quantity,
        unitPrice: i.unitPrice,
        subtotal: i.subtotal,
        createdAt: i.createdAt,
      })),
    } as OrderPrimitives);
  }

  static toPrisma(order: Order): any {
    const p = order.toPrimitives();
    return {
      id: p.id,
      tenantId: p.tenantId,
      orderNumber: p.orderNumber,
      cartId: p.cartId,
      checkoutSessionId: p.checkoutSessionId,
      customerId: p.customerId,
      guestEmail: p.guestEmail,
      status: p.status,
      currency: p.currency,
      subtotal: p.subtotal,
      shippingAmount: p.shippingAmount,
      discountAmount: p.discountAmount,
      taxAmount: p.taxAmount,
      total: p.total,
      shippingMethodCode: p.shippingMethodCode,
      paymentMethodCode: p.paymentMethodCode,
      paymentStatus: p.paymentStatus,
      fulfillmentStatus: p.fulfillmentStatus,
      cancellationReason: p.cancellationReason,
      cancelledAt: p.cancelledAt,
      confirmedAt: p.confirmedAt,
      processingStartedAt: p.processingStartedAt,
      readyAt: p.readyAt,
      shippedAt: p.shippedAt,
      deliveredAt: p.deliveredAt,
      expiredAt: p.expiredAt,
      carrierCode: p.carrierCode,
      trackingNumber: p.trackingNumber,
      trackingUrl: p.trackingUrl,
      version: p.version,
      items: p.items.map(i => ({
        id: i.id,
        orderId: i.orderId,
        productVariantId: i.productVariantId,
        sku: i.sku,
        productNameSnapshot: i.productNameSnapshot,
        variantNameSnapshot: i.variantNameSnapshot,
        quantity: i.quantity,
        unitPrice: i.unitPrice,
        subtotal: i.subtotal,
      })),
    };
  }
}
