export const PRICING_ERROR_CODES = {
  PRICE_LIST_NOT_FOUND: 'PRICE_LIST_NOT_FOUND',
  PRICE_LIST_CODE_ALREADY_EXISTS: 'PRICE_LIST_CODE_ALREADY_EXISTS',
  PRICE_LIST_INVALID_STATUS: 'PRICE_LIST_INVALID_STATUS',
  PRICE_LIST_DEFAULT_CONFLICT: 'PRICE_LIST_DEFAULT_CONFLICT',
  VARIANT_PRICE_NOT_FOUND: 'VARIANT_PRICE_NOT_FOUND',
  VARIANT_PRICE_ALREADY_EXISTS: 'VARIANT_PRICE_ALREADY_EXISTS',
  INVALID_MONEY_AMOUNT: 'INVALID_MONEY_AMOUNT',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  INVALID_PROMOTION_DATE_RANGE: 'INVALID_PROMOTION_DATE_RANGE',
  PROMOTION_PRICE_TOO_HIGH: 'PROMOTION_PRICE_TOO_HIGH',
  NO_APPLICABLE_PRICE: 'NO_APPLICABLE_PRICE',
  PRICING_TENANT_MISMATCH: 'PRICING_TENANT_MISMATCH',
  PRICING_VERSION_CONFLICT: 'PRICING_VERSION_CONFLICT',
  PRICING_INVALID_DATA: 'PRICING_INVALID_DATA',
} as const;

export class PricingException extends Error {
  public readonly code: string;
  constructor(code: string, message: string) {
    super(message);
    this.name = 'PricingException';
    this.code = code;
  }
}
