export const QUEUE_ERROR_CODES = {
  QUEUE_UNAVAILABLE: 'QUEUE_001',
  JOB_TIMEOUT: 'QUEUE_002',
  JOB_FAILED: 'QUEUE_003',
  SERIALIZATION_ERROR: 'QUEUE_004',
  WORKER_ERROR: 'QUEUE_005',
  CONFIGURATION_ERROR: 'QUEUE_006',
  QUEUE_NOT_FOUND: 'QUEUE_007',
  QUEUE_CLOSED: 'QUEUE_008',
  INVALID_JOB_DATA: 'QUEUE_009',
  WORKER_NOT_FOUND: 'QUEUE_010',
} as const;
