export const VARIANT_ERROR_CODES = {
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  VARIANT_SKU_ALREADY_EXISTS: 'VARIANT_SKU_ALREADY_EXISTS',
  VARIANT_INVALID_SKU: 'VARIANT_INVALID_SKU',
  VARIANT_BARCODE_INVALID: 'VARIANT_BARCODE_INVALID',
  VARIANT_ATTRIBUTE_COMBINATION_EXISTS: 'VARIANT_ATTRIBUTE_COMBINATION_EXISTS',
  VARIANT_INVALID_STATUS_TRANSITION: 'VARIANT_INVALID_STATUS_TRANSITION',
  VARIANT_PRODUCT_NOT_FOUND: 'VARIANT_PRODUCT_NOT_FOUND',
  VARIANT_TENANT_MISMATCH: 'VARIANT_TENANT_MISMATCH',
  VARIANT_VERSION_CONFLICT: 'VARIANT_VERSION_CONFLICT',
  VARIANT_DELETED: 'VARIANT_DELETED',
  VARIANT_INVALID_DATA: 'VARIANT_INVALID_DATA',
  VARIANT_DUPLICATE_ATTRIBUTES: 'VARIANT_DUPLICATE_ATTRIBUTES',
  VARIANT_DEFAULT_ALREADY_EXISTS: 'VARIANT_DEFAULT_ALREADY_EXISTS',
} as const;

export class VariantException extends Error {
  public readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'VariantException';
    this.code = code;
  }
}
