export const INVENTORY_ERROR_CODES = {
  WAREHOUSE_NOT_FOUND: 'WAREHOUSE_NOT_FOUND',
  WAREHOUSE_CODE_ALREADY_EXISTS: 'WAREHOUSE_CODE_ALREADY_EXISTS',
  INVENTORY_ITEM_NOT_FOUND: 'INVENTORY_ITEM_NOT_FOUND',
  INVENTORY_ALREADY_INITIALIZED: 'INVENTORY_ALREADY_INITIALIZED',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_STOCK_QUANTITY: 'INVALID_STOCK_QUANTITY',
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_ALREADY_EXISTS: 'RESERVATION_ALREADY_EXISTS',
  RESERVATION_INVALID_STATUS: 'RESERVATION_INVALID_STATUS',
  RESERVATION_EXPIRED: 'RESERVATION_EXPIRED',
  TRANSFER_SAME_WAREHOUSE: 'TRANSFER_SAME_WAREHOUSE',
  INVENTORY_TENANT_MISMATCH: 'INVENTORY_TENANT_MISMATCH',
  INVENTORY_VERSION_CONFLICT: 'INVENTORY_VERSION_CONFLICT',
  INVENTORY_INVALID_DATA: 'INVENTORY_INVALID_DATA',
} as const;

export class InventoryException extends Error {
  public readonly code: string;
  constructor(code: string, message: string) {
    super(message);
    this.name = 'InventoryException';
    this.code = code;
  }
}
