export const AUTH_CONSTANTS = {
  MAX_CONCURRENT_SESSIONS: 5,
  IDLE_TIMEOUT_MINUTES: 30,
  ABSOLUTE_TIMEOUT_MINUTES: 1440,
  SESSION_TTL_SECONDS: 7 * 24 * 60 * 60,
  SESSION_PREFIX: 'session:',
  USER_SESSIONS_PREFIX: 'user_sessions:',
  DEVICE_PREFIX: 'device:',
  USER_DEVICES_PREFIX: 'user_devices:',
  TRUSTED_DEVICE_TTL_DAYS: 30,
  REMEMBER_ME_TTL_DAYS: 30,
} as const;
