export const IDENTITY_ERROR_CODES = {
  USER_ID_INVALID: 'USER_ID_INVALID',
  ORGANIZATION_ID_INVALID: 'ORGANIZATION_ID_INVALID',
  BRANCH_ID_INVALID: 'BRANCH_ID_INVALID',
  ROLE_ID_INVALID: 'ROLE_ID_INVALID',
  PERMISSION_ID_INVALID: 'PERMISSION_ID_INVALID',
  INVITATION_ID_INVALID: 'INVITATION_ID_INVALID',
  EMAIL_INVALID_LENGTH: 'EMAIL_INVALID_LENGTH',
  EMAIL_INVALID_FORMAT: 'EMAIL_INVALID_FORMAT',
  USERNAME_INVALID_LENGTH: 'USERNAME_INVALID_LENGTH',
  USERNAME_INVALID_FORMAT: 'USERNAME_INVALID_FORMAT',
  DISPLAY_NAME_INVALID_LENGTH: 'DISPLAY_NAME_INVALID_LENGTH',
  PHONE_INVALID_FORMAT: 'PHONE_INVALID_FORMAT',
  DOCUMENT_INVALID_LENGTH: 'DOCUMENT_INVALID_LENGTH',
  DOCUMENT_INVALID_FORMAT: 'DOCUMENT_INVALID_FORMAT',
  AVATAR_INVALID_LENGTH: 'AVATAR_INVALID_LENGTH',
  TIMEZONE_INVALID: 'TIMEZONE_INVALID',
  LOCALE_INVALID_FORMAT: 'LOCALE_INVALID_FORMAT',
  LOCALE_UNSUPPORTED: 'LOCALE_UNSUPPORTED',
  LANGUAGE_UNSUPPORTED: 'LANGUAGE_UNSUPPORTED',
  SLUG_INVALID_LENGTH: 'SLUG_INVALID_LENGTH',
  SLUG_INVALID_FORMAT: 'SLUG_INVALID_FORMAT',
  SLUG_ALREADY_EXISTS: 'SLUG_ALREADY_EXISTS',
  USER_TYPE_INVALID: 'USER_TYPE_INVALID',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  CANNOT_DELETE_SUPER_ADMIN: 'CANNOT_DELETE_SUPER_ADMIN',
  PROFILE_UPDATE_DENIED: 'PROFILE_UPDATE_DENIED',
  DOCUMENT_TYPE_INVALID: 'DOCUMENT_TYPE_INVALID',
  ORGANIZATION_INVALID_STATUS_TRANSITION: 'ORGANIZATION_INVALID_STATUS_TRANSITION',
  ORGANIZATION_INVALID_TIER_UPGRADE: 'ORGANIZATION_INVALID_TIER_UPGRADE',
  ORGANIZATION_MUST_BE_SUSPENDED: 'ORGANIZATION_MUST_BE_SUSPENDED',
  INVITATION_TARGET_INVALID: 'INVITATION_TARGET_INVALID',
  INVITATION_NOT_ALLOWED: 'INVITATION_NOT_ALLOWED',
  INVITATION_CANNOT_ACCEPT: 'INVITATION_CANNOT_ACCEPT',
  INVITATION_CANNOT_RESEND: 'INVITATION_CANNOT_RESEND',
  INVITATION_ALREADY_PENDING: 'INVITATION_ALREADY_PENDING',
} as const;

export const IDENTITY_CONSTANTS = {
  MAX_EMAIL_LENGTH: 254,
  MIN_USERNAME_LENGTH: 3,
  MAX_USERNAME_LENGTH: 50,
  MIN_DISPLAY_NAME_LENGTH: 1,
  MAX_DISPLAY_NAME_LENGTH: 200,
  MAX_AVATAR_URL_LENGTH: 2048,
  DOCUMENT_MIN_LENGTH: 3,
  DOCUMENT_MAX_LENGTH: 20,
  MIN_SLUG_LENGTH: 2,
  MAX_SLUG_LENGTH: 100,
  INVITATION_EXPIRATION_DAYS: 7,
  MAX_AUTH_PROVIDERS: 10,
  MAX_MEMBERSHIPS: 100,
} as const;

export const DEFAULT_ORGANIZATION_TIER = 'free' as const;
export const DEFAULT_USER_TYPE = 'customer' as const;
export const DEFAULT_LOCALE = 'es_AR' as const;
export const DEFAULT_LANGUAGE = 'es' as const;
export const DEFAULT_TIMEZONE = 'America/Argentina/Buenos_Aires' as const;
export const INVITATION_EXPIRATION_DAYS = 7;
