export const API_KEY_ERROR_CODES = {
  KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  KEY_EXPIRED: 'API_KEY_EXPIRED',
  KEY_REVOKED: 'API_KEY_REVOKED',
  KEY_INVALID: 'API_KEY_INVALID',
  KEY_INVALID_FORMAT: 'API_KEY_INVALID_FORMAT',
  KEY_ALREADY_REVOKED: 'API_KEY_ALREADY_REVOKED',
  KEY_ROTATION_FAILED: 'API_KEY_ROTATION_FAILED',
  KEY_LIMIT_EXCEEDED: 'API_KEY_LIMIT_EXCEEDED',
  KEY_HASH_FAILED: 'API_KEY_HASH_FAILED',
  KEY_PREFIX_INVALID: 'API_KEY_PREFIX_INVALID',
  SERVICE_ACCOUNT_NOT_FOUND: 'SERVICE_ACCOUNT_NOT_FOUND',
  SERVICE_ACCOUNT_DISABLED: 'SERVICE_ACCOUNT_DISABLED',
  SERVICE_ACCOUNT_SUSPENDED: 'SERVICE_ACCOUNT_SUSPENDED',
  SERVICE_ACCOUNT_LIMIT_EXCEEDED: 'SERVICE_ACCOUNT_LIMIT_EXCEEDED',
  SCOPE_INVALID: 'SCOPE_INVALID',
  SCOPE_NOT_ASSIGNED: 'SCOPE_NOT_ASSIGNED',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  BRANCH_MISMATCH: 'BRANCH_MISMATCH',
  MACHINE_AUTH_FAILED: 'MACHINE_AUTH_FAILED',
  GRACE_PERIOD_EXPIRED: 'GRACE_PERIOD_EXPIRED',
} as const;

export class ApiKeyException extends Error {
  public readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'ApiKeyException';
    this.code = code;
  }
}
