export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES_IN: '15m',
  REFRESH_TOKEN_EXPIRES_IN: '7d',
  PASSWORD_RESET_TOKEN_EXPIRES_IN: '1h',
  EMAIL_VERIFICATION_TOKEN_EXPIRES_IN: '24h',
  SESSION_EXPIRES_IN_MS: 7 * 24 * 60 * 60 * 1000,
  MAX_LOGIN_ATTEMPTS: 5,
  LOGIN_ATTEMPTS_WINDOW_MS: 15 * 60 * 1000,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  CLOCK_SKEW_SECONDS: 30,
  BLACKLIST_CLEANUP_INTERVAL_MS: 60 * 60 * 1000,
} as const;
