export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';

export const PRISMA_SERVICE = 'PRISMA_SERVICE';

export const DATABASE_MODULE_OPTIONS = 'DATABASE_MODULE_OPTIONS';

export const DEFAULT_CONNECTION_RETRIES = 5;

export const DEFAULT_CONNECTION_RETRY_DELAY = 2000;

export const DEFAULT_QUERY_TIMEOUT = 30_000;

export const DEFAULT_POOL_MIN = 2;

export const DEFAULT_POOL_MAX = 10;
