export const CATALOG_ERROR_CODES = {
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_ALREADY_EXISTS: 'CATEGORY_SLUG_ALREADY_EXISTS',
  CATEGORY_INVALID_STATUS_TRANSITION: 'CATEGORY_INVALID_STATUS_TRANSITION',
  CATEGORY_ARCHIVED: 'CATEGORY_ARCHIVED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  CATEGORY_INVALID_DATA: 'CATEGORY_INVALID_DATA',
  CATEGORY_TENANT_MISMATCH: 'CATEGORY_TENANT_MISMATCH',
  CATEGORY_VERSION_CONFLICT: 'CATEGORY_VERSION_CONFLICT',
  CATEGORY_INVALID_PARENT: 'CATEGORY_INVALID_PARENT',
  CATEGORY_CIRCULAR_REFERENCE: 'CATEGORY_CIRCULAR_REFERENCE',
  COLLECTION_NOT_FOUND: 'COLLECTION_NOT_FOUND',
  COLLECTION_SLUG_ALREADY_EXISTS: 'COLLECTION_SLUG_ALREADY_EXISTS',
  COLLECTION_INVALID_STATUS_TRANSITION: 'COLLECTION_INVALID_STATUS_TRANSITION',
  COLLECTION_ARCHIVED: 'COLLECTION_ARCHIVED',
  COLLECTION_DELETED: 'COLLECTION_DELETED',
  COLLECTION_INVALID_DATA: 'COLLECTION_INVALID_DATA',
  COLLECTION_TENANT_MISMATCH: 'COLLECTION_TENANT_MISMATCH',
  COLLECTION_VERSION_CONFLICT: 'COLLECTION_VERSION_CONFLICT',
  COLLECTION_INVALID_DATES: 'COLLECTION_INVALID_DATES',
} as const;

export class CatalogException extends Error {
  public readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'CatalogException';
    this.code = code;
  }
}
